from setuptools import setup
import os

print(os.path.dirname(__file__))

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

APP = ["menuscript/menuscript.py"]
APP_NAME = "MenuScript"
DATA_FILES = [("menuscript/resources")]
OPTIONS = {
    "argv_emulation": True,
    "iconfile": "menuscript/resources/imgs/icon.icns",
    "plist": {
        "LSUIElement": True,
        "CFBundleGetInfoString": "MenuScript",
        "CFBundleIdentifier": "com.mubranch.menuscript",
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "NSHumanReadableCopyright": "Copyright © 2023, Mustafa Branch, All Rights Reserved",
    },
    "packages": ["rumps"],
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
